### PR TITLE
Added functionality to the workflow that allows it to deploy Node.JS lambdas to AWS.

### PR DESCRIPTION
**Pull request by Osbaldo-Arellano**
Also updated the README to reflect those changes. Finally, updated go.work to relative paths.

### CODE REVIEW

**Review by Josh-Sanford — APPROVED** [review]
Looks good to me, nice work!

**Review by centurion-chrome — APPROVED** [review]
Looks good to me for using GH workflows, documentation looks great as well. Only thing I could think of adding, maybe in another PR, is adding some error handling should anything fail, and document why (some additional logging).

**Comment by centurion-chrome** [comment]
Also looks like the following error in the Workflow/Jobs needs to be addressed:
`
Run aws-actions/configure-aws-credentials@v1
  with:
    aws-access-key-id: ***
    aws-secret-access-key: ***
    aws-session-token: ***
    aws-region: us-west-1
    audience: sts.amazonaws.com
  env:
    ARTIFACT_NAME: artifact-PR11
Error: The security token included in the request is invalid

`

**Review by Josh-Sanford — COMMENTED** [review]
@Osbaldo-Arellano regarding Ben's last comment, should the region be us-west-2 so it's targeting the Oregon region?

**Comment by Osbaldo-Arellano** [comment]
@Josh-Sanford @rifleben , thanks for the feedback guys. I will change the region and add more error handling in another PR.

**Pull request merged**
